### ISSUE TITLE
Problema con el pase de la tecla S

### ISSUE THREAD

**Issue by rejurime** [rejurime/socketes-tgc#20]
Cuando se juega un poco con la pelota en algun momento se hace parabolico cuando el algoritmo no lo es... pasa cuando uno patea un par de veces....

**Comment by rejurime** [comment]
El problema es cuando la pelota se incrusta en el piso... lo encontre guachin @matiasrege lalalala :smiley:

**Comment by rejurime** [comment]
Encontramos que hay un tema en el calculo la gravedad... hay que hacer un fix en el eje y pero eso implica toca a la esfera y la caja asociada por eso puede qeu se dibuje/calcule mal las colisiones

**Comment by matiasrege** [comment]
Al final era un problema de colisiones con el jugador, ya no deberia volver a pasar.
